from __future__ import annotations

from datetime import date


class ReportWriter:
    """Creates structured Markdown reports from sourced findings."""

    def create_markdown_report(
        self,
        title: str,
        findings: list[dict[str, str]],
        sources: list[str],
    ) -> str:
        safe_title = title.strip().title() or "Research Report"
        lines = [
            f"# {safe_title}",
            "",
            f"Generated: {date.today().isoformat()}",
            "",
            "## Summary",
            "",
        ]
        for finding in findings:
            lines.append(f"- {finding['summary']}")
        lines.extend(["", "## Sources", ""])
        if sources:
            for source in sources:
                lines.append(f"- {source}")
        else:
            lines.append("- No sources available.")
        lines.extend(
            [
                "",
                "## Notes",
                "",
                "This report was generated by the Personal Research Assistant demo using sourced research findings.",
                "",
            ]
        )
        return "\n".join(lines)
