from __future__ import annotations

from datetime import date


class ReportWriter:
    """Creates structured Markdown reports from sourced findings."""

    def create_markdown_report(
        self,
        title: str,
        findings: list[dict[str, object]],
        sources: list[str],
        mode: str = "summary",
    ) -> str:
        if mode == "vector_database_comparison" and findings:
            return self._create_vector_database_report(title, findings, sources)

        safe_title = title.strip().title() or "Research Report"
        lines = [
            f"# {safe_title}",
            "",
            f"Generated: {date.today().isoformat()}",
            "",
            "## Summary",
            "",
        ]
        for finding in findings:
            lines.append(f"- {finding['summary']}")
        lines.extend(["", "## Sources", ""])
        if sources:
            for source in sources:
                lines.append(f"- {source}")
        else:
            lines.append("- No sources available.")
        lines.extend(
            [
                "",
                "## Notes",
                "",
                "This report was generated by the Personal Research Assistant demo using sourced research findings.",
                "",
            ]
        )
        return "\n".join(lines)

    def _create_vector_database_report(
        self,
        title: str,
        findings: list[dict[str, object]],
        sources: list[str],
    ) -> str:
        safe_title = title.strip().title() or "Vector Database Comparison"
        lines = [
            f"# {safe_title}",
            "",
            f"Generated: {date.today().isoformat()}",
            "",
            "## Executive Summary",
            "",
            "Milvus, Weaviate, and Qdrant are all strong open-source vector database choices, but they differ in positioning.",
            "Milvus is the most clearly optimized for large-scale similarity search, Weaviate emphasizes hybrid retrieval and AI-native search, and Qdrant is a compact vector search engine with strong payload filtering.",
            "",
            "## Comparison Table",
            "",
            "| Database | Type / positioning | Key strengths | Common use cases | Source |",
            "| --- | --- | --- | --- | --- |",
        ]

        for item in findings:
            strengths = "; ".join(item.get("key_strengths", []))
            use_cases = "; ".join(item.get("common_use_cases", []))
            source = f"{item.get('source', '')} ({item.get('source_label', 'source')})"
            lines.append(
                f"| {item.get('database', 'Unknown')} | {item.get('type_positioning', 'N/A')} | {strengths} | {use_cases} | {source} |"
            )

        lines.extend(
            [
                "",
                "## Database Details",
                "",
            ]
        )

        for item in findings:
            lines.extend(
                [
                    f"### {item.get('database', 'Unknown')}",
                    "",
                    f"**Type / positioning:** {item.get('type_positioning', 'N/A')}",
                    "",
                    "**Key strengths:**",
                ]
            )
            for strength in item.get("key_strengths", []):
                lines.append(f"- {strength}")
            lines.extend(["", "**Common use cases:**"])
            for use_case in item.get("common_use_cases", []):
                lines.append(f"- {use_case}")
            lines.extend(
                [
                    "",
                    f"**Source:** {item.get('source', 'N/A')} ({item.get('source_label', 'source')})",
                    "",
                ]
            )

        lines.extend(
            [
                "## Recommendation / Selection Guidance",
                "",
                "- Choose Milvus when the priority is scale and a straightforward production vector database.",
                "- Choose Weaviate when hybrid search and AI-native retrieval are the main product goals.",
                "- Choose Qdrant when you want a focused vector search engine with strong filtering and a clean operational surface.",
                "",
                "## Sources",
                "",
            ]
        )

        for source in sources:
            lines.append(f"- {source}")

        lines.extend(
            [
                "",
                "## Limitations",
                "",
                "This report is a concise evaluation based on public official/product pages. It is useful for quick comparison, but deeper benchmark testing is still recommended before production selection.",
                "",
            ]
        )
        return "\n".join(lines)
